// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: currencyExchange.proto

package Java.currencyExchange;

/**
 * Protobuf type {@code currencyExchange.ExchangeArguments}
 */
public  final class ExchangeArguments extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:currencyExchange.ExchangeArguments)
        ExchangeArgumentsOrBuilder {
  // Use ExchangeArguments.newBuilder() to construct.
  private ExchangeArguments(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExchangeArguments() {
    currencyType_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ExchangeArguments(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            currencyType_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CurrencyExchangeProto.internal_static_currencyExchange_ExchangeArguments_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CurrencyExchangeProto.internal_static_currencyExchange_ExchangeArguments_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ExchangeArguments.class, Builder.class);
  }

  public static final int CURRENCYTYPE_FIELD_NUMBER = 1;
  private int currencyType_;
  /**
   * <code>.currencyExchange.CurrencyType currencyType = 1;</code>
   */
  public int getCurrencyTypeValue() {
    return currencyType_;
  }
  /**
   * <code>.currencyExchange.CurrencyType currencyType = 1;</code>
   */
  public CurrencyType getCurrencyType() {
    CurrencyType result = CurrencyType.valueOf(currencyType_);
    return result == null ? CurrencyType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (currencyType_ != CurrencyType.PLN.getNumber()) {
      output.writeEnum(1, currencyType_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (currencyType_ != CurrencyType.PLN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, currencyType_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ExchangeArguments)) {
      return super.equals(obj);
    }
    ExchangeArguments other = (ExchangeArguments) obj;

    boolean result = true;
    result = result && currencyType_ == other.currencyType_;
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENCYTYPE_FIELD_NUMBER;
    hash = (53 * hash) + currencyType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ExchangeArguments parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExchangeArguments parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExchangeArguments parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExchangeArguments parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExchangeArguments parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExchangeArguments parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExchangeArguments parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ExchangeArguments parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ExchangeArguments parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ExchangeArguments parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ExchangeArguments parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ExchangeArguments parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ExchangeArguments prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code currencyExchange.ExchangeArguments}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:currencyExchange.ExchangeArguments)
          ExchangeArgumentsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CurrencyExchangeProto.internal_static_currencyExchange_ExchangeArguments_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CurrencyExchangeProto.internal_static_currencyExchange_ExchangeArguments_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ExchangeArguments.class, Builder.class);
    }

    // Construct using currencyExchange.ExchangeArguments.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      currencyType_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CurrencyExchangeProto.internal_static_currencyExchange_ExchangeArguments_descriptor;
    }

    public ExchangeArguments getDefaultInstanceForType() {
      return ExchangeArguments.getDefaultInstance();
    }

    public ExchangeArguments build() {
      ExchangeArguments result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ExchangeArguments buildPartial() {
      ExchangeArguments result = new ExchangeArguments(this);
      result.currencyType_ = currencyType_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ExchangeArguments) {
        return mergeFrom((ExchangeArguments)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ExchangeArguments other) {
      if (other == ExchangeArguments.getDefaultInstance()) return this;
      if (other.currencyType_ != 0) {
        setCurrencyTypeValue(other.getCurrencyTypeValue());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ExchangeArguments parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ExchangeArguments) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int currencyType_ = 0;
    /**
     * <code>.currencyExchange.CurrencyType currencyType = 1;</code>
     */
    public int getCurrencyTypeValue() {
      return currencyType_;
    }
    /**
     * <code>.currencyExchange.CurrencyType currencyType = 1;</code>
     */
    public Builder setCurrencyTypeValue(int value) {
      currencyType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.currencyExchange.CurrencyType currencyType = 1;</code>
     */
    public CurrencyType getCurrencyType() {
      CurrencyType result = CurrencyType.valueOf(currencyType_);
      return result == null ? CurrencyType.UNRECOGNIZED : result;
    }
    /**
     * <code>.currencyExchange.CurrencyType currencyType = 1;</code>
     */
    public Builder setCurrencyType(CurrencyType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      currencyType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.currencyExchange.CurrencyType currencyType = 1;</code>
     */
    public Builder clearCurrencyType() {
      
      currencyType_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:currencyExchange.ExchangeArguments)
  }

  // @@protoc_insertion_point(class_scope:currencyExchange.ExchangeArguments)
  private static final ExchangeArguments DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ExchangeArguments();
  }

  public static ExchangeArguments getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExchangeArguments>
      PARSER = new com.google.protobuf.AbstractParser<ExchangeArguments>() {
    public ExchangeArguments parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExchangeArguments(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExchangeArguments> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ExchangeArguments> getParserForType() {
    return PARSER;
  }

  public ExchangeArguments getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

