// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: currencyExchange.proto

package currencyExchange;

public interface CountedExchangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:currencyExchange.CountedExchange)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.currencyExchange.CurrencyType from_currencyType = 1;</code>
   */
  int getFromCurrencyTypeValue();
  /**
   * <code>.currencyExchange.CurrencyType from_currencyType = 1;</code>
   */
  currencyExchange.CurrencyType getFromCurrencyType();

  /**
   * <code>.currencyExchange.CurrencyType to_currencyType = 2;</code>
   */
  int getToCurrencyTypeValue();
  /**
   * <code>.currencyExchange.CurrencyType to_currencyType = 2;</code>
   */
  currencyExchange.CurrencyType getToCurrencyType();

  /**
   * <code>uint32 res = 3;</code>
   */
  int getRes();
}
