// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: currencyExchange.proto

package currencyExchange;

public interface ExchangeArgumentsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:currencyExchange.ExchangeArguments)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.currencyExchange.CurrencyType currencyType = 1;</code>
   */
  int getCurrencyTypeValue();
  /**
   * <code>.currencyExchange.CurrencyType currencyType = 1;</code>
   */
  currencyExchange.CurrencyType getCurrencyType();
}
