// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: currencyExchange.proto

package currencyExchange;

/**
 * Protobuf type {@code currencyExchange.ExchangeArguments}
 */
public  final class ExchangeArguments extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:currencyExchange.ExchangeArguments)
    ExchangeArgumentsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExchangeArguments.newBuilder() to construct.
  private ExchangeArguments(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExchangeArguments() {
    currencyType_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ExchangeArguments(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            currencyType_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return currencyExchange.CurrencyExchangeProto.internal_static_currencyExchange_ExchangeArguments_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return currencyExchange.CurrencyExchangeProto.internal_static_currencyExchange_ExchangeArguments_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            currencyExchange.ExchangeArguments.class, currencyExchange.ExchangeArguments.Builder.class);
  }

  public static final int CURRENCYTYPE_FIELD_NUMBER = 1;
  private int currencyType_;
  /**
   * <code>.currencyExchange.CurrencyType currencyType = 1;</code>
   */
  public int getCurrencyTypeValue() {
    return currencyType_;
  }
  /**
   * <code>.currencyExchange.CurrencyType currencyType = 1;</code>
   */
  public currencyExchange.CurrencyType getCurrencyType() {
    currencyExchange.CurrencyType result = currencyExchange.CurrencyType.valueOf(currencyType_);
    return result == null ? currencyExchange.CurrencyType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (currencyType_ != currencyExchange.CurrencyType.PLN.getNumber()) {
      output.writeEnum(1, currencyType_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (currencyType_ != currencyExchange.CurrencyType.PLN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, currencyType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof currencyExchange.ExchangeArguments)) {
      return super.equals(obj);
    }
    currencyExchange.ExchangeArguments other = (currencyExchange.ExchangeArguments) obj;

    boolean result = true;
    result = result && currencyType_ == other.currencyType_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENCYTYPE_FIELD_NUMBER;
    hash = (53 * hash) + currencyType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static currencyExchange.ExchangeArguments parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static currencyExchange.ExchangeArguments parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static currencyExchange.ExchangeArguments parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static currencyExchange.ExchangeArguments parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static currencyExchange.ExchangeArguments parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static currencyExchange.ExchangeArguments parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static currencyExchange.ExchangeArguments parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static currencyExchange.ExchangeArguments parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static currencyExchange.ExchangeArguments parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static currencyExchange.ExchangeArguments parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static currencyExchange.ExchangeArguments parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static currencyExchange.ExchangeArguments parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(currencyExchange.ExchangeArguments prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code currencyExchange.ExchangeArguments}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:currencyExchange.ExchangeArguments)
      currencyExchange.ExchangeArgumentsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return currencyExchange.CurrencyExchangeProto.internal_static_currencyExchange_ExchangeArguments_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return currencyExchange.CurrencyExchangeProto.internal_static_currencyExchange_ExchangeArguments_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              currencyExchange.ExchangeArguments.class, currencyExchange.ExchangeArguments.Builder.class);
    }

    // Construct using currencyExchange.ExchangeArguments.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      currencyType_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return currencyExchange.CurrencyExchangeProto.internal_static_currencyExchange_ExchangeArguments_descriptor;
    }

    public currencyExchange.ExchangeArguments getDefaultInstanceForType() {
      return currencyExchange.ExchangeArguments.getDefaultInstance();
    }

    public currencyExchange.ExchangeArguments build() {
      currencyExchange.ExchangeArguments result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public currencyExchange.ExchangeArguments buildPartial() {
      currencyExchange.ExchangeArguments result = new currencyExchange.ExchangeArguments(this);
      result.currencyType_ = currencyType_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof currencyExchange.ExchangeArguments) {
        return mergeFrom((currencyExchange.ExchangeArguments)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(currencyExchange.ExchangeArguments other) {
      if (other == currencyExchange.ExchangeArguments.getDefaultInstance()) return this;
      if (other.currencyType_ != 0) {
        setCurrencyTypeValue(other.getCurrencyTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      currencyExchange.ExchangeArguments parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (currencyExchange.ExchangeArguments) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int currencyType_ = 0;
    /**
     * <code>.currencyExchange.CurrencyType currencyType = 1;</code>
     */
    public int getCurrencyTypeValue() {
      return currencyType_;
    }
    /**
     * <code>.currencyExchange.CurrencyType currencyType = 1;</code>
     */
    public Builder setCurrencyTypeValue(int value) {
      currencyType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.currencyExchange.CurrencyType currencyType = 1;</code>
     */
    public currencyExchange.CurrencyType getCurrencyType() {
      currencyExchange.CurrencyType result = currencyExchange.CurrencyType.valueOf(currencyType_);
      return result == null ? currencyExchange.CurrencyType.UNRECOGNIZED : result;
    }
    /**
     * <code>.currencyExchange.CurrencyType currencyType = 1;</code>
     */
    public Builder setCurrencyType(currencyExchange.CurrencyType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      currencyType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.currencyExchange.CurrencyType currencyType = 1;</code>
     */
    public Builder clearCurrencyType() {
      
      currencyType_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:currencyExchange.ExchangeArguments)
  }

  // @@protoc_insertion_point(class_scope:currencyExchange.ExchangeArguments)
  private static final currencyExchange.ExchangeArguments DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new currencyExchange.ExchangeArguments();
  }

  public static currencyExchange.ExchangeArguments getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExchangeArguments>
      PARSER = new com.google.protobuf.AbstractParser<ExchangeArguments>() {
    public ExchangeArguments parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ExchangeArguments(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExchangeArguments> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExchangeArguments> getParserForType() {
    return PARSER;
  }

  public currencyExchange.ExchangeArguments getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

