// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: currencyExchange.proto

package Java.currencyExchange;

public interface CountedExchangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:currencyExchange.CountedExchange)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.currencyExchange.CurrencyType currencyType = 1;</code>
   */
  int getCurrencyTypeValue();
  /**
   * <code>.currencyExchange.CurrencyType currencyType = 1;</code>
   */
  CurrencyType getCurrencyType();

  /**
   * <code>uint32 res = 2;</code>
   */
  int getRes();
}
